
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LebarBalok = new javax.swing.JTextField();
        TinggiBalok = new javax.swing.JTextField();
        PanjangBalok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BttnBalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BttnKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jrjrBola = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BttnBola = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 380, 40);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Masukkan Lebar     :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Masukkan Tinggi     :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Masukkan Panjang :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 11, 130, 30);
        jPanel1.add(LebarBalok);
        LebarBalok.setBounds(140, 50, 260, 30);
        jPanel1.add(TinggiBalok);
        TinggiBalok.setBounds(140, 90, 260, 30);
        jPanel1.add(PanjangBalok);
        PanjangBalok.setBounds(140, 10, 260, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 50, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 90, 50, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 10, 50, 30);

        BttnBalok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BttnBalok.setText("Hitung");
        BttnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnBalokActionPerformed(evt);
            }
        });
        jPanel1.add(BttnBalok);
        BttnBalok.setBounds(200, 130, 90, 50);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 10, 130, 20);
        jPanel2.add(sisi);
        sisi.setBounds(20, 30, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(150, 30, 40, 30);

        BttnKubus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BttnKubus.setText("Volume");
        BttnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnKubusActionPerformed(evt);
            }
        });
        jPanel2.add(BttnKubus);
        BttnKubus.setBounds(20, 70, 100, 40);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 255, 51));
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(30, 20, 170, 30);

        jrjrBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrjrBolaActionPerformed(evt);
            }
        });
        jPanel3.add(jrjrBola);
        jrjrBola.setBounds(30, 50, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(190, 50, 50, 30);

        BttnBola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BttnBola.setText("Volume");
        BttnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnBolaActionPerformed(evt);
            }
        });
        jPanel3.add(BttnBola);
        BttnBola.setBounds(30, 90, 100, 40);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 80, 520, 290);

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 170, 100);

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(170, 0, 170, 100);

        jPanel6.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(340, 0, 170, 100);

        setBounds(0, 0, 530, 409);
    }// </editor-fold>//GEN-END:initComponents

    private void BttnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnBalokActionPerformed
        // TODO add your handling code here:
        int panjang,lebar,tinggi;
        panjang=Integer.parseInt(PanjangBalok.getText());
        lebar=Integer.parseInt(LebarBalok.getText());
        tinggi=Integer.parseInt(TinggiBalok.getText());
        int hasil=panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah : "+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e, "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BttnBalokActionPerformed

    private void BttnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnKubusActionPerformed
        // TODO add your handling code here:
        int s;
        s=Integer.parseInt(sisi.getText());
        int hasil=s*s*s;
        try{
            JOptionPane.showMessageDialog(null, "Volume Kubus Adalah : "
                    +hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BttnKubusActionPerformed

    private void BttnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari=Integer.parseInt(jrjrBola.getText());
        float hasil=(float)(Math.PI*jari*jari*jari*4/3);
        try{
            JOptionPane.showMessageDialog(null, "Volume Bola Adalah : "
                    +hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BttnBolaActionPerformed

    private void jrjrBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrjrBolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrjrBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnBalok;
    private javax.swing.JButton BttnBola;
    private javax.swing.JButton BttnKubus;
    private javax.swing.JTextField LebarBalok;
    private javax.swing.JTextField PanjangBalok;
    private javax.swing.JTextField TinggiBalok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jrjrBola;
    private javax.swing.JTextField sisi;
    // End of variables declaration//GEN-END:variables
}
